/*
  WORDBOOK — IELTS / TOEFL high-frequency words
  Auto-rotates 5 new words per day.
  Each word:
    word, pos (part of speech), meaning (simple English),
    example, level (ielts / toefl / both)
*/

const WORDS = [
  { word: "ambivalent", pos: "adj", meaning: "having mixed feelings — not sure if you like it or not.", example: "She felt ambivalent about moving to a new city.", level: "both" },
  { word: "conducive", pos: "adj", meaning: "helpful, making something more likely to happen.", example: "A quiet room is conducive to studying.", level: "both" },
  { word: "meticulous", pos: "adj", meaning: "very careful and paying attention to small details.", example: "He is meticulous about keeping his desk clean.", level: "both" },
  { word: "pragmatic", pos: "adj", meaning: "practical — dealing with things in a realistic, useful way.", example: "Her pragmatic approach solved the problem quickly.", level: "both" },
  { word: "profound", pos: "adj", meaning: "very deep or serious — often about ideas or feelings.", example: "The book had a profound effect on my thinking.", level: "both" },
  { word: "resilient", pos: "adj", meaning: "able to recover quickly from tough situations.", example: "Kids are surprisingly resilient after big changes.", level: "both" },
  { word: "scrutinize", pos: "verb", meaning: "to look at something very carefully and critically.", example: "The lawyer scrutinized every line of the contract.", level: "both" },
  { word: "ubiquitous", pos: "adj", meaning: "seemingly everywhere at once.", example: "Smartphones are ubiquitous in modern life.", level: "toefl" },
  { word: "advocate", pos: "verb", meaning: "to publicly support an idea or a cause.", example: "She advocates for stricter environmental laws.", level: "both" },
  { word: "arbitrary", pos: "adj", meaning: "based on random choice, not on any reason or system.", example: "The rules seem arbitrary to me.", level: "both" },
  { word: "coherent", pos: "adj", meaning: "logical and easy to understand; parts fit together.", example: "Her argument was clear and coherent.", level: "both" },
  { word: "comprehensive", pos: "adj", meaning: "including everything; complete.", example: "We need a comprehensive plan for the project.", level: "both" },
  { word: "detrimental", pos: "adj", meaning: "harmful; causing damage.", example: "Too much sugar is detrimental to your health.", level: "both" },
  { word: "elicit", pos: "verb", meaning: "to get a reaction or answer from someone.", example: "The teacher's question elicited many opinions.", level: "toefl" },
  { word: "empirical", pos: "adj", meaning: "based on observation or experiment, not just theory.", example: "The claim needs empirical evidence.", level: "toefl" },
  { word: "endeavor", pos: "noun", meaning: "a serious effort or attempt to do something.", example: "Writing a novel is a huge endeavor.", level: "both" },
  { word: "explicit", pos: "adj", meaning: "clearly stated, leaving no room for confusion.", example: "The instructions were explicit and easy to follow.", level: "both" },
  { word: "feasible", pos: "adj", meaning: "possible and practical to do.", example: "Is your plan actually feasible?", level: "both" },
  { word: "hinder", pos: "verb", meaning: "to make it harder for something to happen.", example: "Bad weather hindered our travel.", level: "both" },
  { word: "implement", pos: "verb", meaning: "to put a plan or system into action.", example: "The company will implement new rules next month.", level: "both" },
  { word: "inevitable", pos: "adj", meaning: "certain to happen; cannot be avoided.", example: "Change is inevitable in any career.", level: "both" },
  { word: "innovative", pos: "adj", meaning: "using new ideas or methods.", example: "She has an innovative approach to teaching.", level: "both" },
  { word: "intricate", pos: "adj", meaning: "very detailed and complicated.", example: "The design has an intricate pattern.", level: "both" },
  { word: "notorious", pos: "adj", meaning: "famous for something bad.", example: "He is notorious for being late.", level: "both" },
  { word: "perceive", pos: "verb", meaning: "to notice or understand something.", example: "How do people perceive our brand?", level: "both" },
  { word: "prevalent", pos: "adj", meaning: "very common in a place or time.", example: "This slang is prevalent among teenagers.", level: "both" },
  { word: "reluctant", pos: "adj", meaning: "not wanting to do something.", example: "She was reluctant to share her opinion.", level: "both" },
  { word: "substantial", pos: "adj", meaning: "large in size, amount, or importance.", example: "They made a substantial donation.", level: "both" },
  { word: "sustainable", pos: "adj", meaning: "able to continue for a long time without harm.", example: "We need sustainable energy sources.", level: "both" },
  { word: "tedious", pos: "adj", meaning: "boring and slow.", example: "Filling out forms is tedious work.", level: "both" },
  { word: "underlying", pos: "adj", meaning: "hidden but important; the real cause.", example: "The underlying issue is a lack of trust.", level: "both" },
  { word: "vague", pos: "adj", meaning: "not clear or specific.", example: "Her answer was too vague to be helpful.", level: "both" },
  { word: "vivid", pos: "adj", meaning: "very clear and bright; feels real.", example: "She has a vivid memory of that day.", level: "both" },
  { word: "compelling", pos: "adj", meaning: "very interesting; hard to look away from.", example: "The documentary was absolutely compelling.", level: "both" },
  { word: "diverse", pos: "adj", meaning: "made up of many different things or people.", example: "New York has a diverse population.", level: "both" },
  { word: "eminent", pos: "adj", meaning: "famous and highly respected in a field.", example: "She is an eminent scientist in her field.", level: "toefl" },
  { word: "endorse", pos: "verb", meaning: "to publicly say you support someone or something.", example: "The celebrity endorses the new product.", level: "both" },
  { word: "eradicate", pos: "verb", meaning: "to completely destroy or remove something.", example: "They want to eradicate poverty in the region.", level: "both" },
  { word: "exacerbate", pos: "verb", meaning: "to make a bad situation worse.", example: "Stress exacerbates the symptoms.", level: "toefl" },
  { word: "facilitate", pos: "verb", meaning: "to make something easier to happen.", example: "The app facilitates communication between team members.", level: "both" },
  { word: "fluctuate", pos: "verb", meaning: "to change up and down often.", example: "Stock prices fluctuate every day.", level: "both" },
  { word: "impede", pos: "verb", meaning: "to slow down or block progress.", example: "Heavy traffic impeded our journey.", level: "both" },
  { word: "inherent", pos: "adj", meaning: "a natural, permanent part of something.", example: "There's an inherent risk in extreme sports.", level: "both" },
  { word: "juxtapose", pos: "verb", meaning: "to place two things side by side to compare them.", example: "The essay juxtaposes wealth and poverty.", level: "toefl" },
  { word: "linger", pos: "verb", meaning: "to stay somewhere longer than expected.", example: "The smell of coffee lingered in the room.", level: "both" },
  { word: "lucrative", pos: "adj", meaning: "making a lot of money.", example: "Software engineering is a lucrative field.", level: "both" },
  { word: "mitigate", pos: "verb", meaning: "to make something less severe or harmful.", example: "We took steps to mitigate the risk.", level: "both" },
  { word: "nuance", pos: "noun", meaning: "a small, subtle difference in meaning or feeling.", example: "The word has many nuances in different cultures.", level: "toefl" },
  { word: "obscure", pos: "adj", meaning: "not well known; hard to understand.", example: "The poem uses obscure references.", level: "both" },
  { word: "obsolete", pos: "adj", meaning: "no longer used because something newer exists.", example: "Fax machines are basically obsolete.", level: "both" },
  { word: "ominous", pos: "adj", meaning: "suggesting something bad is going to happen.", example: "The dark clouds looked ominous.", level: "both" },
  { word: "paramount", pos: "adj", meaning: "the most important above everything else.", example: "Safety is paramount in this job.", level: "both" },
  { word: "peripheral", pos: "adj", meaning: "not central; on the edge or less important.", example: "That's a peripheral issue, not the main problem.", level: "toefl" },
  { word: "persistent", pos: "adj", meaning: "continuing to do something even when it's hard.", example: "She's persistent — she never gives up.", level: "both" },
  { word: "plausible", pos: "adj", meaning: "seeming reasonable or likely to be true.", example: "That's a plausible explanation.", level: "both" },
  { word: "predominant", pos: "adj", meaning: "the most common or main one.", example: "Blue is the predominant color in the room.", level: "both" },
  { word: "profound", pos: "adj", meaning: "very deep in meaning or feeling.", example: "It was a profound loss for the family.", level: "both" },
  { word: "prolific", pos: "adj", meaning: "producing a lot of something (books, art, ideas).", example: "She's a prolific writer — 20 novels so far.", level: "both" },
  { word: "prone", pos: "adj", meaning: "likely to do or experience something (often bad).", example: "He's prone to overthinking.", level: "both" },
  { word: "reciprocal", pos: "adj", meaning: "shared or given by both sides.", example: "It's a reciprocal agreement — we both benefit.", level: "toefl" },
  { word: "redundant", pos: "adj", meaning: "unnecessary because it's repeated or extra.", example: "That sentence is redundant, delete it.", level: "both" },
  { word: "refute", pos: "verb", meaning: "to prove that something is not true.", example: "She refuted the accusation with evidence.", level: "toefl" },
  { word: "reluctance", pos: "noun", meaning: "the feeling of not wanting to do something.", example: "He agreed with obvious reluctance.", level: "both" },
  { word: "resemblance", pos: "noun", meaning: "the way one thing looks like another.", example: "The resemblance between the sisters is striking.", level: "both" },
  { word: "significant", pos: "adj", meaning: "important or large enough to matter.", example: "There was a significant drop in sales.", level: "both" },
  { word: "spontaneous", pos: "adj", meaning: "happening naturally without planning.", example: "We had a spontaneous road trip.", level: "both" },
  { word: "stagnant", pos: "adj", meaning: "not moving or changing; without progress.", example: "The economy has been stagnant for years.", level: "both" },
  { word: "static", pos: "adj", meaning: "not moving or changing.", example: "House prices have been static this year.", level: "both" },
  { word: "subsequent", pos: "adj", meaning: "coming after something else in time or order.", example: "The initial meeting was fine, but subsequent ones were tense.", level: "both" },
  { word: "subtle", pos: "adj", meaning: "not obvious; hard to notice.", example: "There's a subtle difference in the two colors.", level: "both" },
  { word: "superficial", pos: "adj", meaning: "only on the surface; not deep or serious.", example: "His knowledge of the topic is superficial.", level: "both" },
  { word: "tangible", pos: "adj", meaning: "real; you can touch or measure it.", example: "We need tangible results, not just promises.", level: "both" },
  { word: "trivial", pos: "adj", meaning: "not important; small.", example: "They argued over trivial things.", level: "both" },
  { word: "unprecedented", pos: "adj", meaning: "never happened or existed before.", example: "The pandemic caused unprecedented changes.", level: "both" },
  { word: "vibrant", pos: "adj", meaning: "full of energy, life, or bright color.", example: "The city has a vibrant nightlife.", level: "both" },
  { word: "warrant", pos: "verb", meaning: "to deserve or need something.", example: "This doesn't warrant a full investigation.", level: "toefl" },
  { word: "yield", pos: "verb", meaning: "to produce a result; to give in.", example: "The experiment yielded interesting results.", level: "both" },
  { word: "abundant", pos: "adj", meaning: "existing in large quantities.", example: "Fruits are abundant in summer.", level: "both" },
  { word: "adverse", pos: "adj", meaning: "bad; harmful; against you.", example: "The medicine has some adverse side effects.", level: "both" },
  { word: "alleviate", pos: "verb", meaning: "to make pain or a problem less severe.", example: "This medicine will alleviate the headache.", level: "both" },
  { word: "ambiguous", pos: "adj", meaning: "having more than one possible meaning; unclear.", example: "The ending of the movie was ambiguous.", level: "both" },
  { word: "articulate", pos: "verb", meaning: "to express thoughts clearly in words.", example: "She articulated her concerns very well.", level: "both" },
  { word: "aspiration", pos: "noun", meaning: "a strong hope or goal for the future.", example: "Her aspiration is to become a doctor.", level: "both" },
  { word: "assert", pos: "verb", meaning: "to state something firmly and confidently.", example: "He asserted his innocence to the police.", level: "both" },
  { word: "candid", pos: "adj", meaning: "honest and direct, sometimes uncomfortably so.", example: "She gave a candid interview about her past.", level: "both" },
  { word: "compensate", pos: "verb", meaning: "to make up for something bad or missing.", example: "The bonus compensates for the long hours.", level: "both" },
  { word: "complacent", pos: "adj", meaning: "satisfied with yourself — often too much so.", example: "Don't get complacent just because you won once.", level: "toefl" },
  { word: "concise", pos: "adj", meaning: "short and clear; not using extra words.", example: "Please keep your answer concise.", level: "both" },
  { word: "confront", pos: "verb", meaning: "to face a difficult person or situation directly.", example: "She confronted her fear of public speaking.", level: "both" },
  { word: "consequent", pos: "adj", meaning: "happening as a result of something.", example: "The rain and consequent flooding damaged homes.", level: "both" },
  { word: "constitute", pos: "verb", meaning: "to make up or form something.", example: "Water constitutes 70% of the human body.", level: "toefl" },
  { word: "contemplate", pos: "verb", meaning: "to think deeply about something.", example: "She contemplated moving abroad.", level: "both" },
  { word: "controversial", pos: "adj", meaning: "causing a lot of disagreement.", example: "It's a controversial new law.", level: "both" },
  { word: "credible", pos: "adj", meaning: "believable; trustworthy.", example: "Is this a credible source?", level: "both" },
  { word: "curtail", pos: "verb", meaning: "to reduce or limit something.", example: "The company curtailed spending this year.", level: "toefl" },
  { word: "deem", pos: "verb", meaning: "to consider or judge something to be a certain way.", example: "The court deemed the evidence insufficient.", level: "toefl" },
  { word: "deficient", pos: "adj", meaning: "not having enough of something needed.", example: "His diet is deficient in vitamins.", level: "both" },
  { word: "denounce", pos: "verb", meaning: "to publicly criticize or condemn someone.", example: "The president denounced the attacks.", level: "both" },
  { word: "deplete", pos: "verb", meaning: "to use up so there's less or none left.", example: "Overfishing has depleted fish populations.", level: "both" },
  { word: "derive", pos: "verb", meaning: "to get something from a particular source.", example: "The word derives from Latin.", level: "both" },
  { word: "diligent", pos: "adj", meaning: "hard-working and careful.", example: "She's a diligent student.", level: "both" },
  { word: "discreet", pos: "adj", meaning: "careful not to attract attention or cause embarrassment.", example: "Please be discreet about this news.", level: "both" },
  { word: "disparate", pos: "adj", meaning: "very different from each other.", example: "The team has members with disparate backgrounds.", level: "toefl" },
  { word: "distinct", pos: "adj", meaning: "clearly different; separate.", example: "There are two distinct groups of customers.", level: "both" },
  { word: "diverge", pos: "verb", meaning: "to go in different directions; to be different.", example: "Their opinions began to diverge.", level: "toefl" },
  { word: "elaborate", pos: "verb", meaning: "to explain something in more detail.", example: "Could you elaborate on your idea?", level: "both" },
  { word: "eloquent", pos: "adj", meaning: "speaking or writing in a beautiful, powerful way.", example: "Her speech was truly eloquent.", level: "both" }
];
